### ISSUE TITLE
Melhorias!

### ISSUE THREAD

**Issue by ErickWendel** [despossivel/serverless-rekognition#1]
Evitar retornar o erro não tratado do servido ao cliente
https://github.com/despossivel/serverless-rekognition/blob/master/analysis/index.js#L99

Não substituir o valor da variável após criadas
https://github.com/despossivel/serverless-rekognition/blob/master/analysis/index.js#L59

Aqui poderia melhorar a legibilidade
https://github.com/despossivel/serverless-rekognition/blob/master/analysis/index.js#L47

```js
async translateWorkingItems(workingItems) {
    const novaLista = []
    for ({Name, Confidence, Parents} of workingItems) {
     
      const [name, parents] = await Promise.all([
                                  this.translateText(name), 
                                  this.translateParents(workingItems[indexItem].Parents)
                                ])
      const confidence = this.confidenceFormat(Confidence)
     novaLista.push({
          Name: name,
         Parents: parents,
         Confidence: confidence,
     })
    }
    return novaLista;
  }  
```

**Comment by despossivel** [comment]
Valeu pelo feedback, vou fazer essas melhorias...

**Comment by ErickWendel** [comment]
> Valeu pelo feedback, vou fazer essas melhorias...

opa! E parabéns pelo projeto!!
